# Model parameters
model_type: "random_forest"
random_seed: 42
test_size: 0.2

# Hyperparameters for Random Forest
random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

# Data processing parameters
data:
  target_column: "price"
  categorical_columns: ["city", "province_name", "location_id", "page_url", "property_type", "location"]
  numerical_columns: ["latitude", "longitude", "baths", "area", "bedrooms", "Total_Area"]